FROM golang:alpine

RUN apk update && apk add --no-cache gcc curl libc-dev git bash make
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.0

RUN mkdir -p /admin/tests

WORKDIR /admin/tests

COPY . .
