version: '3'
services:

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: ["make", "tests"]
    environment:
      SCHEDULERS_ADDR: scheduler:8000
    depends_on:
      kafka:
        condition: service_healthy
      scheduler:
        condition: service_healthy

  scheduler:
    image: etf1/kafka-message-scheduler:mini
    hostname: scheduler
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:8000/info || exit 1"]
      timeout: 5s
      interval: 10s
      retries: 5
    ports:
      - 8000:8000
    # dont remove, dont modify, used for override
    environment:
      BOOTSTRAP_SERVERS:
    
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    healthcheck:
      test: ["CMD-SHELL", "echo 'ruok' | nc -w 2 localhost 2181 | grep imok"]
      interval: 20s
      timeout: 10s
      retries: 10
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # for health check "ruok"
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 20
    ports:
      # Exposes 9092 for external connections to the broker
      # Use kafka:29092 for connections internal on the docker network
      # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
